// A single line of AI commentary shown in the "From the Box" panel.
// Commentary is generated by the Groq AI service after each round/question.

class CommentaryLine {
  final String text;      // The commentary sentence, e.g. "What a shot from Rohit!"
  final int timestamp;    // Unix timestamp (ms) — used to sort lines by time

  const CommentaryLine({
    required this.text,
    required this.timestamp,
  });

  // Build a CommentaryLine from a Firebase / JSON map
  factory CommentaryLine.fromJson(Map<String, dynamic> json) {
    return CommentaryLine(
      text: json['text'] as String,
      timestamp: (json['timestamp'] as int?) ?? 0,
    );
  }

  // Convert to a map for saving to Firebase
  Map<String, dynamic> toJson() {
    return {
      'text': text,
      'timestamp': timestamp,
    };
  }
}
