// A single line of commentary shown in the "From the Box" panel.
// Lines are generated by CommentaryService (Groq AI or fallback templates)
// and stored in Firebase so every player sees them in real time.

class CommentaryLine {
  final String text;    // The commentary sentence
  final String mode;    // 'trivia' or 'hand' — controls the icon shown
  final int timestamp;  // Unix ms — used for ordering

  const CommentaryLine({
    required this.text,
    this.mode = 'trivia',
    required this.timestamp,
  });

  // Build from Firebase / JSON map
  factory CommentaryLine.fromJson(Map<String, dynamic> json) {
    return CommentaryLine(
      text: (json['text'] as String?) ?? '',
      mode: (json['mode'] as String?) ?? 'trivia',
      timestamp: (json['timestamp'] as int?) ?? 0,
    );
  }

  // Convert to map for saving to Firebase
  Map<String, dynamic> toJson() {
    return {
      'text': text,
      'mode': mode,
      'timestamp': timestamp,
    };
  }
}
