// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ12dnV0NAAwrh3jRpPfMOTuF-VTpRs58',
    appId: '1:309575459878:web:92d7ebf39363cc780772e7',
    messagingSenderId: '309575459878',
    projectId: 'crickfest-310a9',
    authDomain: 'crickfest-310a9.firebaseapp.com',
    databaseURL: 'https://crickfest-310a9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'crickfest-310a9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhLAwSWu1qFFAXqgZomYyMI-doFVgWQwo',
    appId: '1:309575459878:android:ce896b14997143620772e7',
    messagingSenderId: '309575459878',
    projectId: 'crickfest-310a9',
    databaseURL: 'https://crickfest-310a9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'crickfest-310a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBP5b15hvz4-lJ1dupSFQygtqgdezf6oM',
    appId: '1:309575459878:ios:58ed0b1995b9e4320772e7',
    messagingSenderId: '309575459878',
    projectId: 'crickfest-310a9',
    databaseURL: 'https://crickfest-310a9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'crickfest-310a9.firebasestorage.app',
    iosBundleId: 'com.example.crickfest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBP5b15hvz4-lJ1dupSFQygtqgdezf6oM',
    appId: '1:309575459878:ios:58ed0b1995b9e4320772e7',
    messagingSenderId: '309575459878',
    projectId: 'crickfest-310a9',
    databaseURL: 'https://crickfest-310a9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'crickfest-310a9.firebasestorage.app',
    iosBundleId: 'com.example.crickfest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJ12dnV0NAAwrh3jRpPfMOTuF-VTpRs58',
    appId: '1:309575459878:web:60b3211427c907cc0772e7',
    messagingSenderId: '309575459878',
    projectId: 'crickfest-310a9',
    authDomain: 'crickfest-310a9.firebaseapp.com',
    databaseURL: 'https://crickfest-310a9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'crickfest-310a9.firebasestorage.app',
  );
}
