import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:firebase_core/firebase_core.dart'; // Firebase initialization

import 'firebase_options.dart';    // Generated by FlutterFire CLI (or use placeholder)
import 'theme/app_theme.dart';
import 'screens/join_screen.dart';
import 'screens/trivia_game_screen.dart';
import 'screens/hand_game_screen.dart';

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------
// Firebase.initializeApp() will be added in Milestone 4 once the
// google-services.json / GoogleService-Info.plist files are in place.
// ---------------------------------------------------------------------------
void main() async {
  // Must be called before any async work in main()
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase using the options from firebase_options.dart.
  // ⚠️  Replace the placeholder values in firebase_options.dart with your
  //    real project config generated by: flutterfire configure
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // Lock the app to portrait orientation
  SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
    DeviceOrientation.portraitDown,
  ]);

  // Immersive dark status bar so the pitch background bleeds to the top edge
  SystemChrome.setSystemUIOverlayStyle(
    const SystemUiOverlayStyle(
      statusBarColor: Colors.transparent,
      statusBarIconBrightness: Brightness.light,
      systemNavigationBarColor: CrickifyColors.pitchDeep,
      systemNavigationBarIconBrightness: Brightness.light,
    ),
  );

  runApp(const CrickifyApp());
}

// ---------------------------------------------------------------------------
// Root widget
// ---------------------------------------------------------------------------
class CrickifyApp extends StatelessWidget {
  const CrickifyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Crickify',
      debugShowCheckedModeBanner: false,

      // Apply the full Crickify design system
      theme: CrickifyTheme.dark,

      // Named routes — one per screen
      initialRoute: '/',
      routes: {
        '/': (_) => const JoinScreen(),
        '/trivia': (_) => const TriviaGameScreen(),
        '/hand': (_) => const HandGameScreen(),
      },
    );
  }
}

